# Generated by Django 4.1.3 on 2022-11-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='measurements',
            field=models.ManyToManyField(to='measurement.measurement'),
        ),
    ]
